print('what do you get when you cross a snowman with a vampire?')
input('?')
print('Frostbite!!')
print('what do dentists call a altronat\'s cavity?')
input('?')
print('A black hole!!')
print('knock knock')
input('?')
print("who's there?")
input('?')
print('Interrupting cow.')
input('?')
print('Interrupting cow wh', end='')
print('-MOO!')