
import pygame, sys, random
from pygame.locals import *


BOARDWIDTH = 4
BOARDHEIGHT = 4
TILESIZE = 80
WINDOWWIDTH = 640
WINDOWHEIGHT = 480
FPS = 30
BLANK = None


#                 R    G    B
BLACK =       (   0,   0,   0)
WHITE =       ( 255, 255, 255)
BRIGHTBLUE =  (   0,  50, 255)
DARKTURQUOISE=(   3,  54,  73)
GREEN =       (   0, 204,   0)


BGCOLOR = DARKTURQUOISE
TILECOLOR = GREEN
BOARDERCOLOR = BRIGHTBLUE
BASICFONTSIZE = 30

BUTTONCOLOR = WHITE
BUTTONTEXTCOLOR = BLACK
MESSAGECOLOR = WHITE

XMARGIN = int((WINDOWWIDTH - (TILESIZE * BOARDWIDTH + (BOARDWIDTH - 1))) / 2)

YMARGIN = int((WINDOWHEIGHT - (TILESIZE * BOARDHEIGHT + (BOARDHEIGHT - 1))) / 2)


UP = 'up'
DOWN = 'down'
LEFT = 'left'
RIGHT = 'right'


def main():
    global FPSCOLOCK, DISPLATSURF, BASICFONT, RESET_SURF, REST_RECT, NEW_SURF, NEW_RECT, SOLVE_SURF, SOLVE_RECT

    pygame.init()
